In [2]:
! nvidia-smi

/bin/bash: nvidia-smi: command not found


What is the difference between GPU and TPU

While GPUs use a flexible, general-purpose architecture, TPUs are purpose-built for machine learning tasks. GPUs consist of thousands of small cores designed to handle multiple tasks simultaneously, whereas TPUs have a more streamlined architecture focused on accelerating tensor operations.

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


## Introduction to Tensors

### Creating tensors

In [4]:
# Scalar
scalar = torch.tensor(7)  # tf.constant()
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# Get tensor back as Python int
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
matrix = torch.tensor([[7,7],
                       [3 ,2]])

matrix

tensor([[7, 7],
        [3, 2]])

In [10]:
matrix.ndim

2

In [11]:
matrix[1][0]

tensor(3)

Random tensors

In [16]:
random_tensor = torch.rand(3,4,) # 3*4 = 12 elements over here
random_tensor

tensor([[9.1849e-01, 5.2061e-01, 8.4050e-01, 4.7952e-01],
        [3.7255e-01, 6.9621e-01, 4.6379e-01, 7.4398e-01],
        [7.1551e-01, 7.8194e-02, 4.4996e-04, 9.4745e-01]])

In [17]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (224,224,3))
random_image_size_tensor

tensor([[[0.4841, 0.4098, 0.2500],
         [0.1302, 0.6313, 0.2564],
         [0.0437, 0.8420, 0.2685],
         ...,
         [0.7361, 0.6796, 0.0035],
         [0.3421, 0.7421, 0.1416],
         [0.6781, 0.7302, 0.3277]],

        [[0.9956, 0.2393, 0.7412],
         [0.1745, 0.6710, 0.4929],
         [0.8895, 0.5827, 0.2028],
         ...,
         [0.3424, 0.9664, 0.2029],
         [0.8679, 0.4544, 0.3981],
         [0.1172, 0.0902, 0.6048]],

        [[0.4814, 0.6712, 0.9617],
         [0.9658, 0.0501, 0.7482],
         [0.5937, 0.6197, 0.2522],
         ...,
         [0.6137, 0.9908, 0.1153],
         [0.0633, 0.7260, 0.1116],
         [0.7389, 0.2586, 0.3919]],

        ...,

        [[0.4673, 0.8365, 0.7900],
         [0.5629, 0.1536, 0.4002],
         [0.1177, 0.1105, 0.5568],
         ...,
         [0.6811, 0.6331, 0.7386],
         [0.7679, 0.2009, 0.2091],
         [0.0048, 0.7528, 0.4023]],

        [[0.1011, 0.6689, 0.7523],
         [0.9514, 0.5966, 0.0066],
         [0.

In [19]:
zeros = torch.zeros(3,4)
ones = torch.ones(3,4)


zeros, ones, ones.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

### Creating a range of tensors and tensors-like

In [22]:
# Use torch.range()
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [24]:
# Creating tensors like
torch.zeros_like(input=torch.arange(0,10,2))

tensor([0, 0, 0, 0, 0])

Tensor Datatypes

In [28]:
# Float32 tensors
float_32 = torch.tensor([3,4], dtype=torch.float32, device = None, requires_grad = False)
float_32.dtype

#Device: What device is your tensor on
#Requiresgrad: Whether or not to track gradients with this tensors operations

torch.float32

Manipulating Tensors (Tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication
* Division
* Matrix Multiplication

In [34]:
tensor = torch.tensor([1,2,3])
tensor_1 = torch.tensor([4,5,6])

tensor + tensor_1 , tensor * tensor_1 , tensor / tensor_1 , tensor - tensor_1, tensor + 10


(tensor([5, 7, 9]),
 tensor([ 4, 10, 18]),
 tensor([0.2500, 0.4000, 0.5000]),
 tensor([-3, -3, -3]),
 tensor([11, 12, 13]))

In [38]:
for i in tensor:
  print(i + 10)

tensor(11)
tensor(12)
tensor(13)


In [40]:
for i in tensor:
  print(i * tensor_1 / 10)

tensor([0.4000, 0.5000, 0.6000])
tensor([0.8000, 1.0000, 1.2000])
tensor([1.2000, 1.5000, 1.8000])


# Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning

1. Elemen-wise mult.
2. Matrix mult.



In [58]:
A = torch.tensor([[1,2,3],
                 [4,5,6]])

A

tensor([[1, 2, 3],
        [4, 5, 6]])

In [65]:
B = torch.tensor([[7,8],
                  [9,10],
                  [11,12]])

In [66]:
torch.matmul(A,B)

tensor([[ 58,  64],
        [139, 154]])

Tensor Aggregations

In [68]:
torch.min(A)

tensor(1)

In [69]:
torch.max(A)

tensor(6)

In [72]:
torch.sum(A)

tensor(21)

In [74]:
torch.mean(A, dtype=torch.float32)

tensor(3.5000)

# Reshaping, Viewing, Stacking

In [82]:
 # Finding the positional min and max
tensor = torch.arange(10,1000,100)
 tensor.argmin() , tensor.argmax()

(tensor(0), tensor(9))

In [83]:
tensor[0], tensor[9]

(tensor(10), tensor(910))

In [84]:
tensor

tensor([ 10, 110, 210, 310, 410, 510, 610, 710, 810, 910])

In [85]:
tensor[0] = 1

In [86]:
tensor

tensor([  1, 110, 210, 310, 410, 510, 610, 710, 810, 910])

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory
as the original tensor
* Stacking - Combine multiple tensors on top of each other (vstack), side by side (hstack)
* Squeeze - Removes all '1 dim from a tensor
* Unsqueeze - Add a '1' dimension to a target tensor
* Permute - Return a view of the input with dem permuted in a certain way

In [88]:
# Let's create a tensor
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [93]:
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [94]:
 # Change the view
 z = x.view(1,9)
 z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [95]:
# Changing z changes x
z[:, 0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [96]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x,x])
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [109]:
# torch.squeeze() - removes all single dimensions from a target tensor
tensor = torch.arange(1,10)
tensor = torch.squeeze(tensor)
tensor, tensor.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [108]:
torch.unsqueeze(tensor, dim=1), torch.unsqueeze(tensor,dim=1).shape

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]))

In [121]:
# torch.permute - rearranges the dim of a target tensor in a specified order
x_original = torch.rand(224,224,3)

x_permuted = x_original.permute(2, 0, 1) #shifts axis

x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [122]:
# Create a tensor
import torch
tensor = torch.arange(1,10).reshape(1,3,3)

In [123]:
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [127]:
# Let's index on our new tensor
tensor[0][1]

tensor([4, 5, 6])

In [130]:
tensor[0][2][2]

tensor(9)